### ISSUE TITLE
[v0.2.1] Error: "unexpected argument" when using enums (Regression)

### ISSUE THREAD

**Issue by Whateverayn** [KZNS/cjk-unbreak#6]
Hi, thank you for developing this package.

I encountered a compilation error when using `cjk-unbreak:0.2.1`.
In my usage, the error occurs when I use simple enum lists (`+ item`).
This code works perfectly with **v0.2.0**, so it seems to be a regression in v0.2.1.

### Minimal Reproduction

```typ
#import "@preview/cjk-unbreak:0.2.1": remove-cjk-break-space
#show: remove-cjk-break-space

+ hoge
+ fuga

```

### Error Message

The compilation fails with `error: unexpected argument` in `transform-childs.typ`.

```text
error: unexpected argument
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:74:39
   │
74 │      return (it.func())(..named-params, ..positional-params)
   │                                           ^^^^^^^^^^^^^^^^^^^

```

<details>
<summary>Full Stack Trace</summary>

```text
help: error occurred in this call of function `reconstruct`
    ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:112:8
    │
112 │         reconstruct(it, fields, positional-params)
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
    ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:106:23
    │
106 │             x.map(i => transform-func(i))
    │                        ^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `map`
    ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:106:12
    │
106 │             x.map(i => transform-func(i))
    │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:85:18
   │
85 │       let child = transform-func(it.child)
   │                   ^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `remove-cjk-break-space`
   ┌─ @preview/cjk-unbreak:0.2.1/transform-childs.typ:82:8
   │
82 │         transform-func(item)
   │         ^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `transform-childs`
   ┌─ @preview/cjk-unbreak:0.2.1/remove-cjk-break-space.typ:27:9
   │
27 │   rest = transform-childs(rest, remove-cjk-break-space)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

</details>

### Environment

* Typst Web App / CLI (0.14.2)
* cjk-unbreak version: 0.2.1 (0.2.0 works fine)

It seems like `it.func()` (the constructor for the element) is receiving arguments it doesn't expect during the reconstruction process in `transform-childs.typ`.

**Comment by KZNS** [comment]
Thanks for the issue! I think #4 has fixed the problem. I will release v0.2.2 later.
